import type { BusinessModel } from "@/lib/types";
import { base } from "./helpers";

// ビジネスモデル図鑑シード(要件 8-7 / 17)
export const businessModels: BusinessModel[] = [
  {
    ...base({ id: "bm-consulting", confidenceLevel: "B", certaintyLevel: "strong" }),
    name: "経営コンサルティング",
    definition: "経営課題に対し、戦略・計画の助言と実行支援を提供するモデル。",
    targetCustomer: "経営課題を抱える企業",
    valueProposition: "専門知見による課題解決と意思決定支援",
    revenueSources: ["顧問料", "プロジェクトフィー"],
    pricingModel: "工数・成果に応じたフィー",
    managementResponsibility: "助言中心(経営責任は限定的)",
    investment: "no",
    equityHolding: "no",
    cxoDispatch: "partial",
    handsOnSupport: "partial",
    performanceFee: "partial",
    exit: "no",
    profitMargin: "高",
    continuity: "中",
    reproducibility: "高",
    scalability: "中",
    mainRisks: ["成果が助言に留まる", "実行は顧客依存"],
    representativeCompanyIds: ["co-funai", "co-livcon"],
    commonWithAbengers: ["戦略・計画策定"],
    diffFromAbengers: ["経営責任と実行、出資まで踏み込まない"],
    tags: ["コンサル"],
  },
  {
    ...base({ id: "bm-handson-vc", confidenceLevel: "B", certaintyLevel: "strong" }),
    name: "ハンズオンVC",
    definition: "出資を通じて経営に関与し、成長とEXITで投資回収を狙うモデル。",
    targetCustomer: "成長を目指すスタートアップ",
    valueProposition: "資金 + 経営支援ネットワーク",
    revenueSources: ["キャピタルゲイン(EXIT)"],
    pricingModel: "出資(株式取得)",
    managementResponsibility: "取締役等として関与(経営受託ではない)",
    investment: "yes",
    equityHolding: "yes",
    cxoDispatch: "partial",
    handsOnSupport: "yes",
    performanceFee: "no",
    exit: "yes",
    profitMargin: "変動大",
    continuity: "低(EXITで終了)",
    reproducibility: "中",
    scalability: "高",
    mainRisks: ["投資回収の不確実性"],
    representativeCompanyIds: ["co-jafco", "co-globis"],
    commonWithAbengers: ["出資", "経営支援"],
    diffFromAbengers: ["日常の経営実行・マーケティング実行までは担わない"],
    tags: ["VC", "投資"],
  },
  {
    ...base({ id: "bm-cxo", confidenceLevel: "B", certaintyLevel: "strong" }),
    name: "CXO派遣・プロシェアリング",
    definition: "必要な期間だけプロ人材・CXOを供給するモデル。",
    targetCustomer: "特定機能の人材が不足する企業",
    valueProposition: "即戦力の経営人材を柔軟に活用",
    revenueSources: ["人材稼働フィー"],
    pricingModel: "稼働時間・期間ベース",
    managementResponsibility: "派遣人材個人が担う範囲に限定",
    investment: "no",
    equityHolding: "no",
    cxoDispatch: "yes",
    handsOnSupport: "yes",
    performanceFee: "partial",
    exit: "no",
    profitMargin: "中",
    continuity: "中",
    reproducibility: "高",
    scalability: "高",
    mainRisks: ["人材品質のばらつき", "組織への定着"],
    representativeCompanyIds: ["co-circulation", "co-visasq"],
    commonWithAbengers: ["CXO人材の供給"],
    diffFromAbengers: ["会社として経営責任・出資を負わない"],
    tags: ["CXO", "プロ人材"],
  },
  {
    ...base({ id: "bm-venturelink", confidenceLevel: "B", certaintyLevel: "strong" }),
    name: "ベンチャー・リンク型FC支援",
    definition: "繁盛店をFC化し、中小企業ネットワークへ高速展開するプラットフォーム型FC支援。",
    targetCustomer: "FC化したいブランド / 新規事業を探す中小企業",
    valueProposition: "仕組み化と加盟開発による全国展開",
    revenueSources: ["コンサルフィー", "加盟金", "ロイヤリティ", "FC本部出資EXIT"],
    pricingModel: "コンサル + 加盟開発 + 出資",
    managementResponsibility: "FC本部構築を支援",
    investment: "yes",
    equityHolding: "partial",
    cxoDispatch: "partial",
    handsOnSupport: "yes",
    performanceFee: "yes",
    exit: "yes",
    profitMargin: "高(拡大期)",
    continuity: "低(モデル破綻リスク)",
    reproducibility: "高",
    scalability: "非常に高い",
    mainRisks: ["未検証モデルの販売", "加盟店収益性の軽視", "短期KPI暴走"],
    representativeCompanyIds: ["co-venturelink"],
    commonWithAbengers: ["FC本部構築", "加盟開発", "出資"],
    diffFromAbengers: ["顧客成果より自社売上を優先しない点で異なる"],
    tags: ["FC", "教訓"],
  },
  {
    ...base({ id: "bm-abengers", confidenceLevel: "A", certaintyLevel: "confirmed" }),
    name: "ABENGERS型共同経営",
    definition:
      "構想・経営・実行・人材・マーケティング・FC化・出資までを一体で担う共同経営型の事業創造モデル。",
    targetCustomer: "価値ある事業を構想・成長させたい経営者・企業",
    valueProposition: "経営全体を共同で担い、成果と利益を顧客と共有する",
    revenueSources: ["受託・顧問", "成果報酬", "株式価値・EXIT"],
    pricingModel: "受託 + 成果報酬 + 出資",
    managementResponsibility: "経営全体(共同経営)",
    investment: "yes",
    equityHolding: "yes",
    cxoDispatch: "yes",
    handsOnSupport: "yes",
    performanceFee: "yes",
    exit: "yes",
    profitMargin: "中〜高",
    continuity: "高(グループ会社化・連続創出)",
    reproducibility: "中(標準化で向上)",
    scalability: "高",
    mainRisks: ["経営資源の集中", "共同経営先の選定"],
    representativeCompanyIds: ["co-abengers"],
    commonWithAbengers: ["定義そのもの"],
    diffFromAbengers: [],
    commonWithKoeni: ["成果へのコミット"],
    diffFromKoeni: ["経営全体を担う点(コエニはマーケティング実行に特化)"],
    tags: ["自社", "共同経営"],
  },
  {
    ...base({ id: "bm-koeni", confidenceLevel: "A", certaintyLevel: "confirmed" }),
    name: "コエニ型マーケティング実行",
    definition: "価値ある商品・サービスを必要とする人へ届け、売上へ変えるマーケティング実行モデル。",
    targetCustomer: "良い商品を持ち売上化したい事業者",
    valueProposition: "集客・販売・ブランド形成の実行",
    revenueSources: ["マーケティング支援フィー", "成果連動"],
    pricingModel: "支援フィー + 成果報酬",
    managementResponsibility: "マーケティング領域",
    investment: "no",
    equityHolding: "no",
    cxoDispatch: "no",
    handsOnSupport: "yes",
    performanceFee: "yes",
    exit: "no",
    profitMargin: "中",
    continuity: "高",
    reproducibility: "高",
    scalability: "高",
    mainRisks: ["媒体・アルゴリズム変化"],
    representativeCompanyIds: ["co-koeni"],
    commonWithKoeni: ["定義そのもの"],
    diffFromKoeni: [],
    diffFromAbengers: ["経営全体は担わない"],
    tags: ["自社グループ", "マーケティング"],
  },
  {
    ...base({ id: "bm-pe", confidenceLevel: "C", certaintyLevel: "hypothesis" }),
    name: "PEファンド",
    definition: "企業を買収し、経営改善・成長を経てEXITで収益を得るモデル(要確認)。",
    targetCustomer: "事業承継・再生・成長を要する企業",
    revenueSources: ["キャピタルゲイン", "配当"],
    investment: "yes",
    equityHolding: "yes",
    cxoDispatch: "yes",
    handsOnSupport: "yes",
    performanceFee: "no",
    exit: "yes",
    representativeCompanyIds: ["co-igpi"],
    tags: ["PE", "要確認"],
  },
  {
    ...base({ id: "bm-studio", confidenceLevel: "C", certaintyLevel: "hypothesis" }),
    name: "スタートアップスタジオ",
    definition: "自社起点で事業を連続的に立ち上げるモデル(要確認)。",
    targetCustomer: "新規事業を創出したい企業・起業家",
    revenueSources: ["株式", "共創フィー"],
    investment: "partial",
    equityHolding: "yes",
    cxoDispatch: "partial",
    handsOnSupport: "yes",
    performanceFee: "partial",
    exit: "yes",
    representativeCompanyIds: ["co-relic"],
    commonWithAbengers: ["事業の連続創出"],
    tags: ["スタジオ", "要確認"],
  },
];
